# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-jetty}
  s.version = "0.1.0.mbc"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Graham Batty"]
  s.date = %q{2010-07-16}
  s.description = %q{Allows you to use Jetty as a Rack adapter in JRuby. Compatible with rackup and rails' Rack support.}
  s.email = %q{graham@stormbrew.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack/handler/jetty.rb",
     "lib/rack_jetty/jars/core-3.1.1.jar",
     "lib/rack_jetty/jars/jetty-6.1.24.jar",
     "lib/rack_jetty/jars/jetty-plus-6.1.24.jar",
     "lib/rack_jetty/jars/jetty-servlet-tester-6.1.24.jar",
     "lib/rack_jetty/jars/jetty-util-6.1.24.jar",
     "lib/rack_jetty/jars/jsp-2.1-jetty-6.1.24.jar",
     "lib/rack_jetty/jars/jsp-api-2.1.jar",
     "lib/rack_jetty/jars/servlet-api-2.5-20081211.jar",
     "lib/rack_jetty/java_input.rb",
     "lib/rack_jetty/servlet_handler.rb",
     "rack-jetty.gemspec",
     "spec/images/image.jpg",
     "spec/rack_handler_jetty_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/stormbrew/rack-jetty}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Very simple (mostly Ruby) implementation of jetty as a pure Rack adapter.}
  s.test_files = [
    "spec/rack_handler_jetty_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rack>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rack>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rack>, [">= 1.0.0"])
  end
end

